### ISSUE TITLE
Docker File Failing To Build

### ISSUE THREAD

**Issue by LukeWFerguson** [zdurham/s3-upload-github-action#6]
`Build container for action use: '/home/runner/work/_actions/zdurham/s3-upload-github-action/master/Dockerfile'.
  /usr/bin/docker build -t c9a4a5:154[2](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:2)2b252de74fda9fe62e80ae2f9479 -f "/home/runner/work/_actions/zdurham/s[3](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:3)-upload-github-action/master/Dockerfile" "/home/runner/work/_actions/zdurham/s3-upload-github-action/master"
  Sending build context to Docker daemon  8.70[4](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:4)kB
  
  Step 1/[5](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:5) : FROM python:3.7-alpine
  3.7-alpine: Pulling from library/python
  31e352740f53: Already exists
  cfcc27[6](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:6)e4459: Pulling fs layer
  8455851b3630: Pulling fs layer
  c41f20535e03: Pulling fs layer
  f053299a814f: Pulling fs layer
  f053299a814f: Waiting
  c41f20535e03: Verifying Checksum
  c41f20535e03: Download complete
  cfcc2[7](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:7)6e4459: Verifying Checksum
  cfcc276e4459: Download complete
  [8](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:8)455851b3630: Verifying Checksum
  8455851b3630: Download complete
  f0532[9](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:9)9a814f: Verifying Checksum
  f053299a814f: Download complete
  cfcc276e4459: Pull complete
  8455851b3630: Pull complete
  c41f20535e03: Pull complete
  f053299a814f: Pull complete
  Digest: sha256:94c0a807604a8da09cf6597f1[10](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:10)80ad8cdb62f9b4dc1e8cb8134e487f33aa15f
  Status: Downloaded newer image for python:3.7-alpine
   ---> fe33630f7d7a
  Step 2/5 : RUN pip install --quiet --no-cache-dir awscli
   ---> Running in ae26dd84fe4a
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        /tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line [11](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:11)8, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 295, in <module>
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/dist.py", line [12](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:12)34, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 3[14](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:14), in run
            self.find_sources()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
            mm.run()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-h0xzup84/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: 23.0.1 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
  The command '/bin/sh -c pip install --quiet --no-cache-dir awscli' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 5.775 seconds before retry.
  /usr/bin/docker build -t c9a4a5:[15](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:15)422b252de74fda9fe62e80ae2f9479 -f "/home/runner/work/_actions/zdurham/s3-upload-github-action/master/Dockerfile" "/home/runner/work/_actions/zdurham/s3-upload-github-action/master"
  Sending build context to Docker daemon  8.704kB
  
  Step 1/5 : FROM python:3.7-alpine
   ---> fe33630f7d7a
  Step 2/5 : RUN pip install --quiet --no-cache-dir awscli
   ---> Running in f078dca3485a
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        /tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-30, you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 1[18](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:18), in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 295, in <module>
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line [20](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:20)1, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 314, in run
            self.find_sources()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 3[22](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:22), in find_sources
            mm.run()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-w2u1offc/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: [23](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:23).0.1 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
  The command '/bin/sh -c pip install --quiet --no-cache-dir awscli' returned a non-zero code: 1
  
  Warning: Docker build failed with exit code 1, back off 8.411 seconds before retry.
  /usr/bin/docker build -t c9a4a5:15422b[25](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:25)2de74fda9fe62e80ae2f9479 -f "/home/runner/work/_actions/zdurham/s3-upload-github-action/master/Dockerfile" "/home/runner/work/_actions/zdurham/s3-upload-github-action/master"
  Sending build context to Docker daemon  8.704kB
  
  Step 1/5 : FROM python:3.7-alpine
   ---> fe33630f7d7a
  Step 2/5 : RUN pip install --quiet --no-cache-dir awscli
   ---> Running in 5bb2e88359b9
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [62 lines of output]
        running egg_info
        writing lib3/PyYAML.egg-info/PKG-INFO
        writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
        writing top-level names to lib3/PyYAML.egg-info/top_level.txt
        /tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/config/setupcfg.py:[29](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:29)3: _DeprecatedConfig: Deprecated config in `setup.cfg`
        !!
        
                ********************************************************************************
                The license_file parameter is deprecated, use license_files instead.
        
                By 2023-Oct-[30](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:30), you need to update your project and remove deprecated calls
                or your builds will no longer be supported.
        
                See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                ********************************************************************************
        
        !!
          parsed = self.parsers.get(option_name, lambda x: x)(value)
        Traceback (most recent call last):
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
            exec(code, locals())
          File "<string>", line 295, in <module>
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 107, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/dist.py", line 1234, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line [31](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:31)4, in run
            self.find_sources()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line [32](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:32)2, in find_sources
            mm.run()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 551, in run
            self.add_defaults()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
            sdist.add_defaults(self)
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
            super().add_defaults()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
            self._add_defaults_ext()
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/command/sdist.py", line [33](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:33)6, in _add_defaults_ext
            self.filelist.extend(build_ext.get_source_files())
          File "<string>", line 201, in get_source_files
          File "/tmp/pip-build-env-zv4uke2g/overlay/lib/python3.7/site-packages/setuptools/_distutils/cmd.py", line [107](https://github.com/TrustBooks/wc-journal-entry/actions/runs/5578753580/jobs/10193371383#step:2:107), in __getattr__
            raise AttributeError(attr)
        AttributeError: cython_sources
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  
  Notice:  A new release of pip is available: 23.0.1 -> 23.2
  Notice:  To update, run: pip install --upgrade pip
  The command '/bin/sh -c pip install --quiet --no-cache-dir awscli' returned a non-zero code: 1
  
Error: Docker build failed with exit code 1`

**Comment by iloverink** [comment]
This seems to be an issue upstream, awscli has a reported issue too. https://github.com/aws/aws-cli/issues/8036

**Comment by JcBernack** [comment]
Seems to have been resolved, see https://github.com/aws/aws-cli/issues/8036#issuecomment-1639136091

**Comment by LukeWFerguson** [comment]
Yes, you are right. My build / deploy is passing now.
